# Generated by Django 5.0.4 on 2024-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
